/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nerbit_crypto_SM_SM4_SM4Decryptor */

#ifndef _Included_com_nerbit_crypto_SM_SM4_SM4Decryptor
#define _Included_com_nerbit_crypto_SM_SM4_SM4Decryptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nerbit_crypto_SM_SM4_SM4Decryptor
 * Method:    sm4DecryptCBC
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_nerbit_crypto_SM_SM4_SM4Decryptor_sm4DecryptCBC
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_nerbit_crypto_SM_SM4_SM4Decryptor
 * Method:    sm4DecryptECB
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_nerbit_crypto_SM_SM4_SM4Decryptor_sm4DecryptECB
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
