/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nerbit_crypto_SM_SM4_SM4Encryptor */

#ifndef _Included_com_nerbit_crypto_SM_SM4_SM4Encryptor
#define _Included_com_nerbit_crypto_SM_SM4_SM4Encryptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nerbit_crypto_SM_SM4_SM4Encryptor
 * Method:    sm4EncryptCBC
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_nerbit_crypto_SM_SM4_SM4Encryptor_sm4EncryptCBC
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_nerbit_crypto_SM_SM4_SM4Encryptor
 * Method:    sm4EncryptECB
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_nerbit_crypto_SM_SM4_SM4Encryptor_sm4EncryptECB
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
