/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nerbit_crypto_SM_SM2_SM2PublicKey */

#ifndef _Included_com_nerbit_crypto_SM_SM2_SM2PublicKey
#define _Included_com_nerbit_crypto_SM_SM2_SM2PublicKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nerbit_crypto_SM_SM2_SM2PublicKey
 * Method:    verifyMessage
 * Signature: ([B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nerbit_crypto_SM_SM2_SM2PublicKey_verifyMessage
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_nerbit_crypto_SM_SM2_SM2PublicKey
 * Method:    encrtpyMessage
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_nerbit_crypto_SM_SM2_SM2PublicKey_encrtpyMessage
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
