/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nerbit_crypto_SM_SM2_SM2Key */

#ifndef _Included_com_nerbit_crypto_SM_SM2_SM2Key
#define _Included_com_nerbit_crypto_SM_SM2_SM2Key
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nerbit_crypto_SM_SM2_SM2Key
 * Method:    generatePubicKey
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_nerbit_crypto_SM_SM2_SM2Key_generatePubicKey
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_nerbit_crypto_SM_SM2_SM2Key
 * Method:    generateSM2KeyPair
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_nerbit_crypto_SM_SM2_SM2Key_generateSM2KeyPair
  (JNIEnv *, jclass);

/*
 * Class:     com_nerbit_crypto_SM_SM2_SM2Key
 * Method:    signMessage
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_nerbit_crypto_SM_SM2_SM2Key_signMessage
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_nerbit_crypto_SM_SM2_SM2Key
 * Method:    decryptMessage
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_nerbit_crypto_SM_SM2_SM2Key_decryptMessage
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
