/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nerbit_crypto_SM_SM3_SM3DigestStateful */

#ifndef _Included_com_nerbit_crypto_SM_SM3_SM3DigestStateful
#define _Included_com_nerbit_crypto_SM_SM3_SM3DigestStateful
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nerbit_crypto_SM_SM3_SM3DigestStateful
 * Method:    SM3Hash256
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_nerbit_crypto_SM_SM3_SM3DigestStateful_SM3Hash256
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_nerbit_crypto_SM_SM3_SM3DigestStateful
 * Method:    SM3Hash256Init_
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_nerbit_crypto_SM_SM3_SM3DigestStateful_SM3Hash256Init_1
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_nerbit_crypto_SM_SM3_SM3DigestStateful
 * Method:    SM3Hash256Pending
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_nerbit_crypto_SM_SM3_SM3DigestStateful_SM3Hash256Pending
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_nerbit_crypto_SM_SM3_SM3DigestStateful
 * Method:    SM3Hash256Final
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_nerbit_crypto_SM_SM3_SM3DigestStateful_SM3Hash256Final
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
